[global]
    run as user = netdata
    web files owner = root
    web files group = root
    bind socket to IP = 0.0.0.0
    default port = 19999
    update every = 1
    memory deduplication (ksm) = yes
    debug log = none
    error log = syslog
    access log = none
    memory mode = dbengine
    page cache size = 32
    dbengine multihost disk space = 1024
    
[plugins]
    tc = no
    idlejitter = no
    netdata monitoring = yes
    
[plugin:apps]
    update every = 2
    command options = without-users without-groups
    
[plugin:proc]
    /proc/meminfo = yes
    /proc/loadavg = yes
    /proc/stat = yes
    /proc/net/dev = yes
    /proc/diskstats = yes
    
[health]
    enabled = yes
    default repeat warning = never
    default repeat critical = never